version: '3.8'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: yourusername
      POSTGRES_PASSWORD: yourpassword
      POSTGRES_DB: parking_lot_db
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: yourusername
      DB_PASS: yourpassword
      DB_NAME: parking_lot_db
    ports:
      - "8080:8080"
    depends_on:
      - db

volumes:
  db_data:
